spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ksearch?serverTimezone=Asia/Seoul
    username: root
    password: qwer1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    cache: false

  redis:
    cluster:
      nodes:
        - 192.168.211.31:6379
        - 192.168.211.32:6379
        - 192.168.211.33:6379

jwt:
  secret:
    key: dongjjiidververysmartandhandsomeguyinjungdongjjiidververysmartandhandsomeguyinjungdongjjiidververysmartandhandsomeguyinjung

logging:
  level:
    root: INFO