- name: Install and configure Logstash server
  hosts: logstash_server
  become: true
  vars:
    kafka_brokers: "kafka1.example.com:9092,kafka2.example.com:9092,kafka3.example.com:9092"
  tasks:
  - name: Install Logstash
    package:
      name: logstash
      state: present
  - name: Configure Logstash
    template:
      src: logstash.conf.j2
      dest: /etc/logstash/conf.d/logstash.conf
  - name: Start Logstash service
    systemd:
      name: logstash
      state: started
      enabled: yes